apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy-1
        image: sarahfares/udagram-reverseproxy-v1:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2024Mi"
            cpu: "250m"
          limits:
            memory: "5024Mi"
            cpu:  "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always  